# yaml-language-server: $schema=schema.json

app:
  http:
    domain: musicgang.org

  jwt:
    secret: secret
    expiresIn: 60 # minutes
    refreshExpiresIn: 20160 # minutes

  auths:
    local: {}

  redis:
    host: localhost
    port: 6379
    password:

  slack:
    webhook: your-slack-webhook-url

  vm:
    maxFuelTank: 100 vKFuel
    maxExecutionTime: 10s
    refuelAmount: 5 vKFuel
    refuelRate: 400ms

  databases:
    postgres:
      database: database_name
      user: database_user
      password: database_password
      host: database_port
      port: 5432
