apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: musicgang
  labels:
    name: nginx-ingress
    app: musicgang
    kind: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - app.musicgang.org
      secretName: musicgang-tls
  rules:
    - host: app.musicgang.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: musicgang-api-service
                port:
                  number: 8888
