apiVersion: v1
kind: ConfigMap
metadata:
  name: musicgang-api-config
  namespace: musicgang
  labels:
    name: musicgang-api-config
    app: musicgang
    kind: config-map
data:
  config.yaml: |
    app:
      auths:

      redis:
        host: redis-service
        port: 6379
        password: ""

      databases:
        postgres:
          database: music-gang-api
          user: postgres
          password: admin
          host: postgres-service
          port: 5432
