---
# yaml-language-server: $schema=https://json.schemastore.org/drone.json

kind: pipeline
type: docker
name: CI-integration-test
trigger:
  branch:
    - master
  event:
    - push
    - custom
    - tag
services:
  - name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: music-gang-ci-test

  - name: redis-db
    image: redis
    environment:
      ALLOW_EMPTY_PASSWORD: yes

steps:
  - name: test
    image: golang:1.17.5
    commands:
      - sleep 15
      - mv drone-ci/config.drone.yaml config.yaml
      - go test ./... -timeout 120s -race -coverprofile=coverage.txt -covermode=atomic

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: drone-ci
      username: drone
      icon_url: https://avatars.githubusercontent.com/u/2181346?s=200&v=4
      template: >
        {{#success build.status}}
          build {{build.number}} succeeded. Good job.
        {{else}}
          build {{build.number}} failed. Fix me please.
        {{/success}}
---
kind: signature
hmac: 962ee6abca9fbfcde94ce8979ac2b50781ddae0fa382afa274e399103082ecdf
