# yaml-language-server: $schema=https://json.schemastore.org/drone.json

kind: pipeline
type: docker
name: CI-integration-test
trigger:
  branch:
    - master
  event:
    - push
    - custom
    - tag
services:
  - name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: music-gang-ci-test

  - name: redis-db
    image: redis
    environment:
      ALLOW_EMPTY_PASSWORD: yes

steps:
  - name: test
    image: golang:1.17.5
    commands:
      - sleep 15
      - mv drone-ci/config.drone.yaml config.yaml
      - go test ./... -timeout 120s -race -coverprofile=coverage.txt -covermode=atomic
