---
# yaml-language-server: $schema=https://json.schemastore.org/drone.json

kind: pipeline
type: docker
name: CI-CD
trigger:
  branch:
    - master
  event:
    - push
    - custom
    - tag
    - cron
    - promote
    - pull_request

services:
  - name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: music-gang-ci-test

  - name: redis-db
    image: redis
    environment:
      ALLOW_EMPTY_PASSWORD: yes

steps:
  - name: test
    image: golang:1.17
    commands:
      - sleep 15
      - mv drone-ci/config.drone.yaml config.yaml
      - go test ./... -timeout 120s -race -coverprofile=coverage.txt -covermode=atomic

  - name: publish-docker-image
    image: plugins/docker
    when:
      status:
        - success
      event:
        - cron
        - tag
        - promote
      target:
        - dev
    settings:
      repo:
        from_secret: docker_repo
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: publish-github-release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_api_key
      title: ${DRONE_TAG}
    when:
      status:
        - success
      event:
        - tag

  - name: deliver-prod-to-k8s
    image: vallard/drone-kube
    settings:
      template: k8s/deployments/musicgang-api-deploy.yml
    when:
      status:
        - success
      event:
        - promote
        - rollback
      target:
        - prod

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: drone-ci
      username: drone
      icon_url: https://avatars.githubusercontent.com/u/2181346?s=200&v=4
      template: >
        {{#success build.status}}
          build {{build.number}} succeeded. Good job.
        {{else}}
          build {{build.number}} failed. Fix me please.
        {{/success}}
---
kind: signature
hmac: 48c27342b4a277b3c238795370c0c2ed19a3dcae9406e6f49658c71e931463c8
