---
# yaml-language-server: $schema=https://json.schemastore.org/drone.json

kind: pipeline
type: docker
name: CI-CD
trigger:
  branch:
    - master
  event:
    - push
    - custom
    - tag
    - cron
    - promote
    - pull_request

services:
  - name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: music-gang-ci-test

  - name: redis-db
    image: redis
    environment:
      ALLOW_EMPTY_PASSWORD: yes

steps:
  - name: test
    image: golang:1.17
    commands:
      - sleep 15
      - mv drone-ci/config.drone.yaml config.yaml
      - go test ./... -timeout 120s -race -coverprofile=coverage.txt -covermode=atomic

  - name: publish-docker-image
    image: plugins/docker
    when:
      event:
        - tag
        - promote
      target:
        exclude:
          - production
    settings:
      repo:
        from_secret: docker_repo
      tags:
        - latest
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: deliver-to-k8s
    image: danielgormly/drone-plugin-kube:0.2.0
    settings:
      build_tag: ${DRONE_TAG}
      server:
        from_secret: KUBE_SERVER
      token:
        from_secret: KUBE_TOKEN
      ca:
        from_secret: KUBE_CA
      template: k8s/deployments/musicgang-api-deploy.yaml
    when:
      event:
        - promote
        - rollback
      target:
        - production

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: drone-ci
      username: drone
      icon_url: https://avatars.githubusercontent.com/u/2181346?s=200&v=4
      template: >
        {{#success build.status}}
          build {{build.number}} succeeded. Good job.
        {{else}}
          build {{build.number}} failed. Fix me please.
        {{/success}}
    when:
      status:
        - failure
        - success
---
kind: signature
hmac: 07839994e0fe8b6cef1fbf7384a71b4815ea55dfd356672eb9931bd5ee6dbf4c
