---
# yaml-language-server: $schema=https://json.schemastore.org/drone.json

kind: pipeline
type: docker
name: CI-CD
trigger:
  branch:
    - master
  event:
    - push
    - custom
    - tag
    - cron
    - promote
    - rollback
    - pull_request

services:
  - name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: music-gang-ci-test

  - name: redis-db
    image: redis
    environment:
      ALLOW_EMPTY_PASSWORD: yes

steps:
  # TESTING
  - name: test
    image: golang:1.17
    commands:
      - sleep 15
      - mv drone-ci/config.drone.yaml config.yaml
      - go test ./... -timeout 120s -race -coverprofile=coverage.txt -covermode=atomic

  # TAGGED DOCKER IMAGE BUILD
  - name: publish-docker-image
    image: plugins/docker
    when:
      event:
        - tag
    settings:
      repo:
        from_secret: docker_repo
      tags:
        - latest
        - ${DRONE_TAG}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  # DEVELOPMENT DOCKER IMAGE BUILD
  - name: publish-docker-image-development
    image: plugins/docker
    when:
      event:
        - promote
        - rollback
      target:
        exclude:
          - production
          - staging
    settings:
      repo:
        from_secret: docker_repo
      tags:
        - ${DRONE_DEPLOY_TO}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  # NIGHTLY BUILD
  - name: nightly-docker-image
    image: plugins/docker
    when:
      event:
        - cron
    settings:
      repo:
        from_secret: docker_repo
      tags:
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  # SLACK NOTIFICATIONS
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: drone-ci
      username: drone
      icon_url: https://avatars.githubusercontent.com/u/2181346?s=200&v=4
      template: >
        {{#success build.status}}
          build {{build.number}} succeeded. Good job.
        {{else}}
          build {{build.number}} failed. Fix me please.
        {{/success}}
    when:
      status:
        - failure
        - success
---
kind: signature
hmac: 1b7dbc073d81e418736d4607ce362290e1e5b83adc36d6038c665abb18cc2d95
