apiVersion: v1
metadata:
  name: musicgang-api-service
  namespace: musicgang
  labels:
    name: musicgang-api-service
    app: musicgang
    kind: cluster-ip
spec:
  selector:
    name: musicgang-api-pod
    app: musicgang
    kind: pod
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
