apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: musicgang
  labels:
    name: postgres-service
    app: musicgang
    kind: cluster-ip
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    app: musicgang
    kind: pod
