apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: musicgang
  labels:
    name: redis-service
    app: musicgang
    kind: cluster-ip
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-pod
    app: musicgang
    kind: pod
