apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: musicgang
  labels:
    name: postgres-pvc
    app: musicgang
    kind: pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi
