apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  labels:
    name: redis-pvc
    app: musicgang
    kind: pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Mi
